# Generated by Django 3.1.6 on 2021-02-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=80),
        ),
    ]
