# Generated by Django 3.1.6 on 2021-02-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Shop', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='comment',
            new_name='review',
        ),
    ]
